### ISSUE TITLE
Compatibility with new FID firmware on ARM based controls

### ISSUE THREAD

**Issue by JasonTraud** [WasatchPhotonics/WasatchUSB#1]
The firmware for the ARM based controls does not respond to the "send_code" function in feature_identification.py This issue seems to be related to the FID_wLength being sent. Changing this value from NULL to 0 seems to produce the desired results and still works with the legacy FX2 based controls.

**Comment by NathanHarrington** [comment]
Repeatable with a device with firmware 10.0.0.2                                                                                   
Calling set_integration_time 0XB2, or cmd_get_image 0XAD will timeout                                                             
with the semaphore timeout has expired message.                                                                                   
                                                                                                                                  
A new version of the fimmware has been developed: 10.0.0.3 This revision                                                          
correctly processes all 0xC0 (host to device) commands. This firmware                                                             
update allows for the reception of integration time change control                                                                
messages, as well as command get image messages. Spectra are returned                                                             
correctly.
